window.PORTFOLIO_PROJECTS = {
  goalflow: {
    id: "goalflow",
    title: "GoalFlow",
    eyebrow: "Enterprise Goal Management",
    subtitle: "Role-based goal planning for employees, managers, and admins with AI suggestions and analytics.",
    image: "assets/project/goalflow-banner.svg",
    github: "https://github.com/sharmaVishal2/GoalFlow",
    live: "https://goal-flows.vercel.app/",
    stack: ["Java", "Spring Boot", "React", "PostgreSQL", "JWT", "Groq API"],
    overview: "GoalFlow is an enterprise-style goal management platform that organizes Employee, Manager, and Admin workflows around approvals, quarterly reviews, blockers, AI goal suggestions, and analytics.",
    problem: "Team goals often become scattered across tools, making ownership, blockers, and review cycles difficult for managers to track.",
    solution: "GoalFlow creates role-specific workflows, protected REST APIs, and clear analytics so teams can plan, review, and improve goals in one product surface.",
    architecture: ["React dashboard", "Spring Boot controllers", "Service layer for goal lifecycle", "JWT + RBAC middleware", "PostgreSQL data model", "Groq-powered suggestions", "Analytics views"],
    features: ["Employee, Manager, and Admin roles", "Goal creation, approval, and review cycles", "Blocker tracking", "AI goal suggestions", "Analytics dashboard", "Role-aware access boundaries"],
    screenshots: ["Role-based dashboard", "Goal approval workflow", "Analytics and progress view"],
    challenges: "The main challenge was keeping RBAC strict while preserving a simple user experience across three role types.",
    future: ["Add manager notification flows", "Add OKR templates", "Improve analytics with trend comparisons", "Add audit trails for enterprise readiness"]
  },
  algopush: {
    id: "algopush",
    title: "AlgoPush",
    eyebrow: "Chrome Extension Automation",
    subtitle: "One-click LeetCode-to-GitHub publishing with AI-generated explanations.",
    image: "assets/project/algo-push-banner.svg",
    github: "https://github.com/sharmaVishal2/AlgoPush",
    live: "https://algopush.vercel.app/",
    stack: ["Java", "Spring Boot", "React", "Chrome Extension API", "GitHub REST API", "Groq API"],
    overview: "AlgoPush is a developer productivity tool that helps push LeetCode solutions to GitHub and generate clean explanations through Groq-powered AI.",
    problem: "Developers often solve problems consistently but skip documentation because moving code from LeetCode to GitHub and writing explanations interrupts the workflow.",
    solution: "AlgoPush automates publishing, organizes solutions, and generates concise explanations so coding practice turns into a well-documented public repository.",
    architecture: ["Chrome extension content script", "Popup UI", "GitHub REST API integration", "Groq explanation service", "Repository organization workflow"],
    features: ["One-click LeetCode solution publishing", "GitHub API integration", "AI-generated explanations", "Organizes 100+ solutions", "Lightweight extension workflow", "Cleaner repository documentation"],
    screenshots: ["Extension action state", "GitHub publishing workflow", "AI explanation output"],
    challenges: "The key challenge was keeping the extension workflow lightweight while coordinating LeetCode page data, GitHub API calls, and AI explanation generation.",
    future: ["Add language-specific explanation templates", "Support multiple repository structures", "Add retry handling for API failures", "Add optional README formatting controls"]
  },
  ecommerce: {
    id: "ecommerce",
    title: "E-Commerce Backend",
    eyebrow: "Backend / Security",
    subtitle: "Production-grade commerce API with OAuth2, JWT, role-based access control, and a fully normalized PostgreSQL data model.",
    image: "assets/project/ecommerce-banner.svg",
    github: "https://github.com/sharmaVishal2/E-Commerce-Application-by-Java-Spring-Boot",
    live: null,
    stack: ["Java", "Spring Boot", "Spring Security", "OAuth2", "JWT", "PostgreSQL", "Hibernate", "Maven"],
    overview: "A fully featured e-commerce backend built with Spring Boot that handles the complete product lifecycle — from catalog browsing and cart management to order placement and admin controls. The system enforces strict role-based access so customers, sellers, and admins each operate within clearly defined boundaries, backed by a normalized relational schema designed for consistency and query performance.",
    problem: "Building a commerce backend that feels simple to the frontend while hiding significant complexity underneath is hard. Most student projects skip proper security, use flat data models, or bolt on authentication as an afterthought. The goal here was to do it right from the start — secure by design, with a schema that reflects real domain relationships.",
    solution: "The system uses Spring Security with OAuth2 and JWT to handle authentication and authorization at the filter level, keeping business logic clean. Hibernate manages a normalized PostgreSQL schema with proper foreign keys, cascade rules, and indexed queries. Every endpoint is protected by role checks, and the API contract is consistent and predictable across all resources.",
    architecture: [
      "Spring Boot application layer",
      "Spring Security filter chain with JWT validation",
      "OAuth2 authorization flow",
      "Role-based access control (Customer / Seller / Admin)",
      "Hibernate ORM with normalized PostgreSQL schema",
      "RESTful resource controllers",
      "Service layer with transactional boundaries",
      "Maven build and dependency management"
    ],
    features: [
      "JWT-secured authentication with refresh token support",
      "OAuth2 integration for third-party login",
      "Three-tier RBAC: Customer, Seller, and Admin roles",
      "Product catalog with category hierarchy and search",
      "Cart management with quantity and price validation",
      "Order placement, tracking, and status management",
      "Admin dashboard APIs for inventory and user management",
      "Normalized PostgreSQL schema with referential integrity",
      "Hibernate-managed entity relationships and lazy loading",
      "Consistent REST API contract with proper HTTP semantics"
    ],
    screenshots: ["Product catalog API response", "Order management flow", "Admin inventory view"],
    challenges: "The most demanding part was designing the security layer so that role enforcement happened at the right level — not scattered across service methods but centralized in the filter chain and method-level annotations. Getting OAuth2 and JWT to coexist cleanly, with proper token validation and expiry handling, required careful configuration of the Spring Security filter order and token store.",
    future: [
      "Add Redis caching for product catalog and session tokens",
      "Introduce Elasticsearch for full-text product search",
      "Add payment gateway integration (Razorpay / Stripe)",
      "Build a seller analytics dashboard with revenue metrics",
      "Containerize with Docker and add CI/CD pipeline"
    ]
  }
};
