window.PORTFOLIO_PROJECTS = {
  smarthire: {
    id: "smarthire",
    title: "SmartHire",
    eyebrow: "AI Interview Platform",
    subtitle: "Resume-aware mock interviews with secure Spring Boot APIs and Groq-powered feedback.",
    image: "assets/project/smarthire-banner.svg",
    github: "https://github.com/sharmaVishal2/Smart-Hire-AI-driven-interview-prepation-",
    live: "https://ai-hackfest-mlh.vercel.app/",
    stack: ["Java", "Spring Boot", "React", "PostgreSQL", "JWT", "Groq API (LLaMA 3)"],
    overview: "SmartHire turns a candidate resume into a focused interview preparation flow. It parses resume context, generates technical and HR questions, and returns structured feedback so practice is tied to the candidate's real skills instead of a generic question bank.",
    problem: "Most interview-prep tools ask generic questions and do not use the candidate's own resume as context. That creates wasted practice time and weak feedback loops.",
    solution: "SmartHire uses resume parsing, prompt design, Groq LLaMA inference, and secure API workflows to create a personalized interview loop from upload to feedback.",
    architecture: ["React interview workspace", "Spring Boot REST API", "JWT authentication", "Resume parsing service", "Groq LLaMA orchestration", "PostgreSQL persistence"],
    features: ["Resume parsing and skill extraction", "Personalized technical and HR question generation", "AI-generated answer feedback", "JWT-secured sessions", "Async-friendly backend flow", "Clear interview progression from upload to review"],
    screenshots: ["Resume analysis workflow", "Interview question workspace", "AI feedback response"],
    challenges: "The hardest part was keeping AI output grounded in resume context. The system uses structured prompts and constrained response formats to reduce vague questions and improve feedback quality.",
    future: ["Add role-specific interview tracks", "Persist historical interview performance", "Add admin analytics for question quality", "Introduce RAG over candidate resume sections"]
  },
  goalflow: {
    id: "goalflow",
    title: "GoalFlow",
    eyebrow: "Enterprise Goal Management",
    subtitle: "Role-based goal planning for employees, managers, and admins with AI suggestions and analytics.",
    image: "assets/project/goalflow-banner.svg",
    github: "https://github.com/sharmaVishal2/GoalFlow",
    live: "https://goal-flows.vercel.app/",
    stack: ["Java", "Spring Boot", "React", "PostgreSQL", "JWT", "Groq API"],
    overview: "GoalFlow is an enterprise-style goal management platform that organizes Employee, Manager, and Admin workflows around approvals, quarterly reviews, blockers, AI goal suggestions, and analytics.",
    problem: "Team goals often become scattered across tools, making ownership, blockers, and review cycles difficult for managers to track.",
    solution: "GoalFlow creates role-specific workflows, protected REST APIs, and clear analytics so teams can plan, review, and improve goals in one product surface.",
    architecture: ["React dashboard", "Spring Boot controllers", "Service layer for goal lifecycle", "JWT + RBAC middleware", "PostgreSQL data model", "Groq-powered suggestions", "Analytics views"],
    features: ["Employee, Manager, and Admin roles", "Goal creation, approval, and review cycles", "Blocker tracking", "AI goal suggestions", "Analytics dashboard", "Role-aware access boundaries"],
    screenshots: ["Role-based dashboard", "Goal approval workflow", "Analytics and progress view"],
    challenges: "The main challenge was keeping RBAC strict while preserving a simple user experience across three role types.",
    future: ["Add manager notification flows", "Add OKR templates", "Improve analytics with trend comparisons", "Add audit trails for enterprise readiness"]
  },
  algopush: {
    id: "algopush",
    title: "AlgoPush",
    eyebrow: "Chrome Extension Automation",
    subtitle: "One-click LeetCode-to-GitHub publishing with AI-generated explanations.",
    image: "assets/project/algo-push-banner.svg",
    github: "https://github.com/sharmaVishal2/AlgoPush",
    live: "https://algopush.vercel.app/",
    stack: ["Spring Boot", "React", "Chrome Extension API", "GitHub REST API", "Groq API"],
    overview: "AlgoPush is a developer productivity tool that helps push LeetCode solutions to GitHub and generate clean explanations through Groq-powered AI.",
    problem: "Developers often solve problems consistently but skip documentation because moving code from LeetCode to GitHub and writing explanations interrupts the workflow.",
    solution: "AlgoPush automates publishing, organizes solutions, and generates concise explanations so coding practice turns into a well-documented public repository.",
    architecture: ["Chrome extension content script", "Popup UI", "GitHub REST API integration", "Groq explanation service", "Repository organization workflow"],
    features: ["One-click LeetCode solution publishing", "GitHub API integration", "AI-generated explanations", "Organizes 100+ solutions", "Lightweight extension workflow", "Cleaner repository documentation"],
    screenshots: ["Extension action state", "GitHub publishing workflow", "AI explanation output"],
    challenges: "The key challenge was keeping the extension workflow lightweight while coordinating LeetCode page data, GitHub API calls, and AI explanation generation.",
    future: ["Add language-specific explanation templates", "Support multiple repository structures", "Add retry handling for API failures", "Add optional README formatting controls"]
  }
};
